theme: jekyll-theme-modernist
title: DiveRSE - Supporting EDI within the RSE community
description: The home of a series of talks and related activities for promoting awareness of and supporting EDI within the Research Software Engineering community.
show_downloads: false
 
